[module]
  [module.hugoVersion]
    extended = true
    min = "0.128.0"
[params]
author = "Oliver Bates"
avatar = "/images/my_avatar_cropped.png"
favicon = "/images/my_avatar_cropped.png"
description = "Sharing my knowledge via this blog."
  [[params.social]]
  icon = "brand-github"
  name = "Github"
  url = "https://github.com/oli-kwski"
  [[params.social]]
  icon = "brand-linkedin"
  name = "Linkedin"
  url = "https://www.linkedin.com/in/oli-k"